### ISSUE TITLE
How to shutdown and startup swirly when you want upgrade lived-swilry?

### ISSUE THREAD

**Issue by betachen** [swirlycloud/swirlyc#88]
Hi mark,
I 'm wondering how to save the swirly machine status when you want shutdown it.
such as,
It was processing a order in matching loop.
then it catched a signal like as "SIGUSR" or anyone else for shutdown, how to process the status of this order?

**Comment by marayl** [comment]
Hi There (sorry, I don't know your name),

I recently added rudimentary support for a sqlite backend. Orders and executions are saved in the database. However, the logic to recover the state of the order-book on startup is not yet implemented. If this is important for you, then I will gladly make it a priority. Incidentally, if you have any other feature requests or suggestions, then please send them to me.

Regarding signal handling, I expect the integrity of the book to be maintained if the process is interrupted by a signal, but more testing needs to be done here to weed-out any nasty corner cases. It is of course possibility for a process to be shutdown before the user has received an order update, but these updates will be available when the service comes back online (once I have implemented the feature mentioned above).

Does this answer your question?

P.S. I will add a couple of tasks to track these items.

Regards,
Mark

**Comment by betachen** [comment]
Hi mark,
My name is hao chen, a fresh trade system developer comes from China.
Now we consider to use swirly which integrates blockchain technology to build a new kind exchange system for digital assets like as bitcoins or any else asset if anyone want to issue it.

Sure, if you can, it's better for us. Finally it's up to your schedule.
hmm, Is that possible to use multi-thread in swirly for working task?

Thanks & Regards,
hao

**Comment by marayl** [comment]
Hi Hao,

Your idea is very interesting and exactly the kind I had in mind for Swirly. I will do my utmost to assist you where I can. May I ask what sort of timelines you have in mind for your project?

I will spend some time this weekend writing a roadmap for Swirly so that you have greater insight into the future direction of the project. In addition, I will add some more tasks to the issue tracker so that we can create some milestones that hopefully align with your plans.

Regarding threading, and scalability more generally, I certainly do intend to move database persistence off the critical path and perhaps even into a separate process. The matching process itself is currently sub-microsecond by my measurements and I have plans to improve this further. (See swirly_bench program.)

There are numerous other options besides, the most obvious would be to partition the workload by Market across a cluster of Swirly instances, and use Nginx as a reverse proxy that routes requests based on Market. Think of Swirly as a microservice. The main challenge here would be aggregating/joining the user's data in a distributed cache of some kind. I aim to have a proof of concept up and running by the end of the year on Amazon EC2.

May I also ask if you have any plans for user authentication and authorisation?

Regards,
Mark

**Comment by betachen** [comment]
Hi Mark,

Oh, Great! thanks a lot for your kindly help.
hmm, I will send you the work plan/project architecture/user cases via email(hao.chen@viewfin.com)
We are focus on decentralization digital assets exchange, would you like to join us for technology guide?

We found that mongoose is not the best solution for swirly even threading.
I mean separate process in task working thread and assignment thread, not only mongoose threading.

Now we have already use nginx for swirly,
In our architecture, we add two sub-systems, which are pre-matching for validate accounts&balances(user data), and post-matching for process tickers data for front-end.

Regarding microservice,I want to know how to deploy swirly clusters? is that mean must have load-balance for swirly? or  nginx only? but lots of markets if we have 100 markets, what should swirly do?

Does you have any consensus algorithm for clusters like as Paxos,Raft?
We think of use multi-broadcast in pre-matching for 3 swirlys.

Thanks & Regards,
hao

**Comment by betachen** [comment]
here is our exchange website, but not English support yet, will add soon.
https://www.bithft.com/index.php?ctl=view&act=view

also support swirly api, some diference with origin swirly:
https://www.bithft.com/api/rec/asset
https://www.bithft.com/api/view/ticker/CNYGLC
https://www.bithft.com/api/view/depth/CNYGLC
https://www.bithft.com/api/view/trades/CNYGLC

**Comment by marayl** [comment]
Hi Hao,

I am going to close this issue now and reply to you offline.

Regards,
Mark
